Repository googleapis/java-dataproc, pull requests merged in 2020-09, with the labels that each got.

#282 chore: generate CODEOWNERS from templates
  .repo-metadata.json
Labels: automerge, cla: yes

#283 chore: update codeowner team alias
  .repo-metadata.json
Labels: automerge, cla: yes

#285 fix: extra code in new sample
  samples/snippets/src/main/java/Quickstart.java
  samples/snippets/src/main/java/SubmitJob.java
  samples/snippets/src/test/java/QuickstartTest.java
Labels: cla: yes

#281 chore: regenerate README
  README.md
  synth.metadata
Labels: api: dataproc, cla: yes, context: none

#287 chore: regenerate common templates
  .github/CODEOWNERS
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#288 chore: regenerate templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: partial

#299 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#300 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: dataproc, automerge, cla: yes

#307 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#309 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
