Repository googleapis/java-dataproc, pull requests merged in 2020-12, with the labels that each got.

#392 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: dataproc, automerge, cla: yes, context: full

#396 chore: updating codeowners with api-dataproc team
  .repo-metadata.json
Labels: api: dataproc, automerge, cla: yes

#397 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dataproc, automerge, cla: yes

#400 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dataproc, automerge, cla: yes

#398 chore: regenerate common templates
  .github/CODEOWNERS
  synth.metadata
Labels: api: dataproc, automerge, cla: yes, context: none

#407 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dataproc, automerge, cla: yes

#410 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dataproc, automerge, cla: yes

#412 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: dataproc, automerge, cla: yes, context: full

#415 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: dataproc, cla: yes, context: full, merge
