Repository googleapis/java-dataproc, pull requests merged in 2020-05, with the labels that each got.

#185 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  .github/workflows/ci.yaml
  .kokoro/build.bat
  synth.metadata
Labels: cla: yes, context: full

#186 chore: update CONTRIBUTING.md to include code formatting
  CONTRIBUTING.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#191 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
