Repository googleapis/java-dataproc, pull requests merged in 2020-06, with the labels that each got.

#199 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#203 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#202 docs: change relative URLs to absolute URLs to fix broken links.
  proto-google-cloud-dataproc-v1/src/main/java/com/google/cloud/dataproc/v1/PrestoJob.java
  proto-google-cloud-dataproc-v1/src/main/proto/google/cloud/dataproc/v1/jobs.proto
  proto-google-cloud-dataproc-v1beta2/src/main/java/com/google/cloud/dataproc/v1beta2/PrestoJob.java
  proto-google-cloud-dataproc-v1beta2/src/main/proto/google/cloud/dataproc/v1beta2/jobs.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#205 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#207 fix: dataproc/v1 raise timeouts in gapic v2
  google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/stub/ClusterControllerStubSettings.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#208 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#213 fix: fix LRO polling and workflow template timeouts
  google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/stub/ClusterControllerStubSettings.java
  google-cloud-dataproc/src/main/java/com/google/cloud/dataproc/v1/stub/WorkflowTemplateServiceStubSettings.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#219 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#221 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#225 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#226 feat: promote to GA
  .repo-metadata.json
  README.md
  synth.metadata
Labels: cla: yes

#228 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-dataproc/pom.xml
  grpc-google-cloud-dataproc-v1/pom.xml
  grpc-google-cloud-dataproc-v1beta2/pom.xml
  pom.xml
  proto-google-cloud-dataproc-v1/pom.xml
  proto-google-cloud-dataproc-v1beta2/pom.xml
Labels: cla: yes

#233 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#242 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
