Repository googleapis/java-dataproc, pull requests merged in 2021-05, with the labels that each got.

#536 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: dataproc, automerge, cla: yes, context: none

#537 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: dataproc, automerge, cla: yes

#538 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: dataproc, automerge, cla: yes

#541 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: dataproc, automerge, cla: yes, context: full

#546 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: dataproc, automerge, cla: yes, context: full

#551 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dataproc, automerge, cla: yes

#552 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: dataproc, automerge, cla: yes, context: full

#557 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: dataproc, automerge, cla: yes, context: full

#560 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dataproc, automerge, cla: yes

#562 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dataproc, automerge, cla: yes
