Repository googleapis/java-dataproc, pull requests merged in 2021-04, with the labels that each got.

#499 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dataproc, automerge, cla: yes

#503 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dataproc, automerge, cla: yes

#502 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: dataproc, automerge, cla: yes, context: full

#505 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dataproc, automerge, cla: yes

#507 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dataproc, automerge, cla: yes

#508 fix: typo
  .kokoro/build.sh
  synth.metadata
Labels: api: dataproc, automerge, cla: yes, context: full

#376 chore: update QuickstartTest to use StdOutCaptureRule
  samples/snippets/src/test/java/QuickstartTest.java
Labels: api: dataproc, cla: yes

#512 fix: release scripts from issuing overlapping phases
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: dataproc, automerge, cla: yes, context: full

#514 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dataproc, automerge, cla: yes

#529 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dataproc, automerge, cla: yes

#534 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dataproc, automerge, cla: yes
